#!/bin/php
<?php require 'vendor/autoload.php';

use AccountGen\Ptc\Generator;
use Illuminate\Database\Capsule\Manager as Capsule;

$db = include 'config/database.php';
$db['driver'] = 'mysql';

$capsule = (new Capsule);
$capsule->addConnection($db);
$capsule->setAsGlobal();
$capsule->bootEloquent();

$options = getopt('u::m::n::', ['unique::', 'multiples::username::']);

$custom = $options['username'] ?? $options['n'] ?? null;
$unique = $options['unique'] ?? $options['u'] ?? 1;
$multiples = $options['multiples'] ?? $options['m'] ?? 15;
//'someUsername##?#';

echo '#username;email;password;dob;country'.PHP_EOL;

$factory = new Generator;

for ($i = 0; $i < $unique; $i++) {
    $accounts = $factory->generateBatch($multiples, $i === 0 ? $custom : null);

    foreach ($accounts as $account) {
        echo $account.PHP_EOL;
    }
}

# vim: syntax=php
