#!/usr/bin/php
<?php require 'vendor/autoload.php';

use AccountGen\Accounts\GenerateCommand;
use AccountGen\Accounts\ListCommand;
use AccountGen\Instances\RegenCommand;
use AccountGen\Instances\UpdateCommand;
use AccountGen\Services\ServiceCommand;
use Illuminate\Database\Capsule\Manager as Capsule;
use Symfony\Component\Console\Application;

$db = include 'config/database.php';
$db['driver'] = 'mysql';

$capsule = (new Capsule);
$capsule->addConnection($db);
$capsule->setAsGlobal();
$capsule->bootEloquent();

$app = new Application();
$app->add(new GenerateCommand);
$app->add(new ListCommand);
$app->add(new RegenCommand);
$app->add(new UpdateCommand);
$app->add(new ServiceCommand);
$app->run();

# vim: syntax=php
